//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Diagnostics;

namespace VanillaSSinn3r.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [DefaultSettingValue("0")]
        [UserScopedSetting]
        [DebuggerNonUserCode]
        public int DefaultRange
        {
            get
            {
                return (int)this["DefaultRange"];
            }
            set
            {
                this["DefaultRange"] = value;
            }
        }

        [DefaultSettingValue("1.5708")]
        [UserScopedSetting]
        [DebuggerNonUserCode]
        public float DefaultFOV
        {
            get
            {
                return (float)this["DefaultFOV"];
            }
            set
            {
                this["DefaultFOV"] = value;
            }
        }

        [DefaultSettingValue("false")]
        [UserScopedSetting]
        [DebuggerNonUserCode]
        public bool DefaultRangeBool
        {
            get
            {
                return (bool)this["DefaultRangeBool"];
            }
            set
            {
                this["DefaultRangeBool"] = value;
            }
        }

        [DefaultSettingValue("false")]
        [UserScopedSetting]
        [DebuggerNonUserCode]
        public bool DefaultFOVBool
        {
            get
            {
                return (bool)this["DefaultFOVBool"];
            }
            set
            {
                this["DefaultFOVBool"] = value;
            }
        }

        [DefaultSettingValue("false")]
        [UserScopedSetting]
        [DebuggerNonUserCode]
        public bool DefaultCamDistBool
        {
            get
            {
                return (bool)this["DefaultCamDistBool"];
            }
            set
            {
                this["DefaultCamDistBool"] = value;
            }
        }

        [DefaultSettingValue("false")]
        [UserScopedSetting]
        [DebuggerNonUserCode]
        public bool DefaultFreezeCamBool
        {
            get
            {
                return (bool)this["DefaultFreezeCamBool"];
            }
            set
            {
                this["DefaultFreezeCamBool"] = value;
            }
        }

        [DefaultSettingValue("50")]
        [UserScopedSetting]
        [DebuggerNonUserCode]
        public int DefaultCamDist
        {
            get
            {
                return (int)this["DefaultCamDist"];
            }
            set
            {
                this["DefaultCamDist"] = value;
            }
        }

    }
}
